version: 2

jobs:
    build:
        docker:
            # Specify the version you desire here
            - image: circleci/php:7.4-node-browsers

        steps:
            - checkout

            - run:
                name: Install MySQL driver
                command: |
                    sudo docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
                    sudo docker-php-ext-install zip bcmath pdo_mysql

            - run:
                name: "Prepare Environment"
                command: |
                    sudo apt update
                    sudo docker-php-ext-install zip

            # Download and cache dependencies
            - restore_cache:
                keys:
                    # "composer.lock" can be used if it is committed to the repo
                    - v1-dependencies-{{ checksum "composer.json" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-

            - run:
                name: "Install Dependencies"
                command: composer install -n --prefer-dist

            - save_cache:
                key: v1-dependencies-{{ checksum "composer.json" }}
                paths:
                    - ./vendor

            # prepare the database
            - run:
                name: "Create Environment file and generate app key"
                command: |
                    mv .env.example .env
                    php artisan key:generate

            - run:
                name: "Set JWT"
                command: php artisan jwt:secret

            # run tests with phpunit
            - run:
                name: "Run Tests"
                command: ./vendor/bin/phpunit
